kind: pipeline
type: docker
name: un-nom
steps:
  - name: build react
    image: lowess/preact-cli
    commands:
      - export BASE_URL=https://${DRONE_REPO_OWNER}.github.io/preact-hugo
      - preact create ${DRONE_REPO}#${DRONE_COMMIT} martini
      - cd martini
      - npm install
      - npm run build 
  - name: slack
    image: plugins/slack
    settings:
      webhook: 
          from_secret : Slack
      username:
        from_secret : github_username
      password:
        from_secret : github_password
        pages_directory: martini/dist