kind: pipeline
type: docker
name: un-nom

steps:
  - name: hello-world
    image: lowess/preact-cli
    environment:
      BASE_URL: ${DRONE_REPO_OWNER}.github.io/preact-hugo/
    commands:
      - preact create ${DRONE_REPO}#${DRONE_COMMIT} martini
      - cd martini
      - npm install
      - npm run build 
  - name: slack
    image: plugins/slack
    settings:
      webhook: 
          from_secret : Slack
      templates: >
      {{#success build.status}}
         https://rickrolled.fr/
      {{else}}
        ??? :dogshit:
      {{/success}}