kind: pipeline
type: docker
name: un-nom
hugo_env: &hugo_env
  BASE_URL: https://${DRONE_REPO_OWNER,,}.github.io/${DRONE_REPO_NAME}/
steps:
  - name: hello-world
    image: lowess/preact-cli
    commands:
      - preact create ${DRONE_REPO}#${DRONE_COMMIT} martini
      - cd martini
      - npm install
      - npm run build 
  - name: slack
    image: plugins/slack
    settings:
      webhook: 
          from_secret : Slack
      templates: >
        {{#success build.status}}
         https://rickrolled.fr/
        {{else}}
          ??? :dogshit:
        {{/success}}