kind: pipeline
type: docker
name: un-nom

steps:
  - name: hello-world
    image: lowess/preact-cli
    commands:
      - preact create Boutillier-Cyril/preact-hugo martini
      - cd martini
      - npm install
      - npm run build
    notify:
      - name: slack
        image: plugins/slack
        settings:
          webhook: 
              from secret : Slack