kind: pipeline
type: docker
name: un-nom

steps:
  - name: hello-world
    image: lowess/preact-cli
    commands:
      - preact create Boutillier-Cyril/preact-hugo martini
      - cd martini
      - npm install
      - npm run build
  - name: slack
    image: plugins/slack
    settings:
      webhook: 
          from_secret : Slack
      templates: >
        Qu'est ce qu'on s'amuse