kind: pipeline
type: docker
name: un-nom

steps:
  - name: hello-world
    image: lowess/preact-cli
    environment :
        SLACK: 
            from secret : Slack
    commands:
      - preact create Boutillier-Cyril/preact-hugo martini
      - cd martini
      - npm install
      - npm start
